using Pos.Application;
namespace Pos.Infrastructure.Tests;
public sealed class DeviceEnrollmentTests
{
 [Fact] public async Task Invitation_is_hashed_and_redeem_is_idempotent_for_same_device(){await using var t=await TestDatabase.CreateAsync();var a=await t.SeedTenantAsync("E");var service=new DeviceEnrollmentService(t.Db,new FakeTokenService());var ctx=new SyncTenantContext(a.Business.Id,a.Business.GlobalId,a.Branch.Id,a.Branch.GlobalId,a.Device.Id,a.Device.GlobalId,a.User.Id,a.User.GlobalId,a.User.Role,a.Device.Mode);var inv=await service.CreateInvitationAsync(ctx,new CreateDeviceEnrollmentRequest(15),CancellationToken.None);var stored=t.Db.DeviceEnrollmentTokens.Single();Assert.False(stored.TokenHash.Contains(inv.Code,StringComparison.Ordinal));var gid=Guid.NewGuid();var request=new RedeemDeviceEnrollmentRequest(inv.Code,a.User.Username,"StrongPass123!","Owner tablet",gid);var first=await service.RedeemAsync(request,CancellationToken.None);var second=await service.RedeemAsync(request,CancellationToken.None);Assert.NotNull(first);Assert.NotNull(second);Assert.Equal(gid,first!.DeviceGlobalId);Assert.Equal(1,t.Db.Devices.Count(x=>x.GlobalId==gid));Assert.Equal(1,t.Db.SyncChanges.Count(x=>x.EntityGlobalId==gid));}
 [Fact] public async Task Revoked_invitation_is_rejected(){await using var t=await TestDatabase.CreateAsync();var a=await t.SeedTenantAsync("X");var service=new DeviceEnrollmentService(t.Db,new FakeTokenService());var ctx=new SyncTenantContext(a.Business.Id,a.Business.GlobalId,a.Branch.Id,a.Branch.GlobalId,a.Device.Id,a.Device.GlobalId,a.User.Id,a.User.GlobalId,a.User.Role,a.Device.Mode);var inv=await service.CreateInvitationAsync(ctx,new CreateDeviceEnrollmentRequest(15),CancellationToken.None);var token=t.Db.DeviceEnrollmentTokens.Single();token.RevokedAt=DateTimeOffset.UtcNow;await t.Db.SaveChangesAsync();var result=await service.RedeemAsync(new RedeemDeviceEnrollmentRequest(inv.Code,a.User.Username,"StrongPass123!","Tablet",Guid.NewGuid()),CancellationToken.None);Assert.Null(result);}
 [Fact] public async Task Seller_cannot_create_invitation(){await using var t=await TestDatabase.CreateAsync();var a=await t.SeedTenantAsync("S",role:"Seller");var service=new DeviceEnrollmentService(t.Db,new FakeTokenService());var ctx=new SyncTenantContext(a.Business.Id,a.Business.GlobalId,a.Branch.Id,a.Branch.GlobalId,a.Device.Id,a.Device.GlobalId,a.User.Id,a.User.GlobalId,a.User.Role,a.Device.Mode);await Assert.ThrowsAsync<UnauthorizedAccessException>(()=>service.CreateInvitationAsync(ctx,new CreateDeviceEnrollmentRequest(15),CancellationToken.None));}
 [Fact] public async Task Admin_from_other_business_cannot_redeem_invitation(){await using var t=await TestDatabase.CreateAsync();var a=await t.SeedTenantAsync("A");var b=await t.SeedTenantAsync("B");var service=new DeviceEnrollmentService(t.Db,new FakeTokenService());var ctx=new SyncTenantContext(a.Business.Id,a.Business.GlobalId,a.Branch.Id,a.Branch.GlobalId,a.Device.Id,a.Device.GlobalId,a.User.Id,a.User.GlobalId,a.User.Role,a.Device.Mode);var inv=await service.CreateInvitationAsync(ctx,new CreateDeviceEnrollmentRequest(15),CancellationToken.None);var result=await service.RedeemAsync(new RedeemDeviceEnrollmentRequest(inv.Code,b.User.Username,"StrongPass123!","B tablet",Guid.NewGuid()),CancellationToken.None);Assert.Null(result);Assert.Null(t.Db.DeviceEnrollmentTokens.Single().UsedAt);}
}
