using System.Text.Json;
using Pos.Application;
using Pos.Domain;
namespace Pos.Infrastructure.Tests;
public sealed class SyncPushTests
{
 [Fact] public async Task Repeated_operation_is_already_processed(){await using var t=await TestDatabase.CreateAsync();var a=await t.SeedTenantAsync("P");var s=new SyncService(t.Db);var ctx=new SyncTenantContext(a.Business.Id,a.Business.GlobalId,a.Branch.Id,a.Branch.GlobalId,a.Device.Id,a.Device.GlobalId,a.User.Id,a.User.GlobalId,a.User.Role,a.Device.Mode);var opId=Guid.NewGuid();var categoryId=Guid.NewGuid();using var doc=JsonDocument.Parse(JsonSerializer.Serialize(new{globalId=categoryId,businessGlobalId=a.Business.GlobalId,name="Seafood",description=(string?)null,active=true,updatedAt=DateTimeOffset.UtcNow,baseServerVersion=(long?)null}));var req=new SyncPushRequest([new SyncOperationDto(opId,"Category",categoryId,"Create",1,doc.RootElement.Clone())]);var first=await s.PushAsync(req,ctx,CancellationToken.None);var second=await s.PushAsync(req,ctx,CancellationToken.None);Assert.Equal("Applied",first.Results.Single().Status);Assert.Equal("AlreadyProcessed",second.Results.Single().Status);Assert.Single(t.Db.Categories.Where(x=>x.GlobalId==categoryId));}
 [Fact] public async Task Stale_catalog_update_returns_conflict_without_overwrite(){await using var t=await TestDatabase.CreateAsync();var a=await t.SeedTenantAsync("C");var cat=new Category{GlobalId=Guid.NewGuid(),BusinessId=a.Business.Id,Name="Server",Active=true,UpdatedAt=DateTimeOffset.UtcNow,ServerVersion=4};t.Db.Categories.Add(cat);await t.Db.SaveChangesAsync();var s=new SyncService(t.Db);var ctx=new SyncTenantContext(a.Business.Id,a.Business.GlobalId,a.Branch.Id,a.Branch.GlobalId,a.Device.Id,a.Device.GlobalId,a.User.Id,a.User.GlobalId,a.User.Role,a.Device.Mode);using var doc=JsonDocument.Parse(JsonSerializer.Serialize(new{globalId=cat.GlobalId,businessGlobalId=a.Business.GlobalId,name="Local stale",description=(string?)null,active=true,updatedAt=DateTimeOffset.UtcNow,baseServerVersion=3}));var r=await s.PushAsync(new SyncPushRequest([new SyncOperationDto(Guid.NewGuid(),"Category",cat.GlobalId,"Update",1,doc.RootElement.Clone())]),ctx,CancellationToken.None);Assert.Equal("Conflict",r.Results.Single().Status);Assert.Equal("Server",t.Db.Categories.Single().Name);}
}
