namespace Pos.Domain;

public sealed class Business { public long Id { get; set; } public Guid GlobalId { get; set; } public string Name { get; set; } = ""; public bool Active { get; set; } = true; public DateTimeOffset CreatedAt { get; set; } public DateTimeOffset UpdatedAt { get; set; } public long ServerVersion { get; set; } = 1; }
public sealed class Branch { public long Id { get; set; } public Guid GlobalId { get; set; } public long BusinessId { get; set; } public string Name { get; set; } = ""; public bool Active { get; set; } = true; public DateTimeOffset CreatedAt { get; set; } public DateTimeOffset UpdatedAt { get; set; } public long ServerVersion { get; set; } = 1; }
public sealed class Device { public long Id { get; set; } public Guid GlobalId { get; set; } public long BranchId { get; set; } public string Name { get; set; } = ""; public string Mode { get; set; } = "PointOfSale"; public bool Active { get; set; } = true; public DateTimeOffset CreatedAt { get; set; } public DateTimeOffset? LastSyncAt { get; set; } public long ServerVersion { get; set; } = 1; }
public sealed class UserAccount { public long Id { get; set; } public Guid GlobalId { get; set; } public long BusinessId { get; set; } public string Name { get; set; } = ""; public string Username { get; set; } = ""; public string PasswordHash { get; set; } = ""; public string PasswordSalt { get; set; } = ""; public string Role { get; set; } = "Seller"; public bool Active { get; set; } = true; public DateTimeOffset CreatedAt { get; set; } public DateTimeOffset UpdatedAt { get; set; } public long ServerVersion { get; set; } = 1; }
public sealed class Category { public long Id { get; set; } public Guid GlobalId { get; set; } public long BusinessId { get; set; } public string Name { get; set; } = ""; public string? Description { get; set; } public bool Active { get; set; } = true; public DateTimeOffset UpdatedAt { get; set; } public long ServerVersion { get; set; } = 1; }
public sealed class Supplier { public long Id { get; set; } public Guid GlobalId { get; set; } public long BusinessId { get; set; } public string Name { get; set; } = ""; public string? ContactName { get; set; } public string? Phone { get; set; } public string? Email { get; set; } public string? Address { get; set; } public string? Notes { get; set; } public bool Active { get; set; } = true; public DateTimeOffset UpdatedAt { get; set; } public long ServerVersion { get; set; } = 1; }
public sealed class Product { public long Id { get; set; } public Guid GlobalId { get; set; } public long BusinessId { get; set; } public Guid? CategoryGlobalId { get; set; } public string Code { get; set; } = ""; public string? Barcode { get; set; } public string Name { get; set; } = ""; public string Presentation { get; set; } = "Piece"; public long SalePriceCents { get; set; } public int MinimumStock { get; set; } public bool Active { get; set; } = true; public DateTimeOffset UpdatedAt { get; set; } public long ServerVersion { get; set; } = 1; }
public sealed class Purchase { public long Id { get; set; } public Guid GlobalId { get; set; } public long BusinessId { get; set; } public long BranchId { get; set; } public long DeviceId { get; set; } public long UserId { get; set; } public Guid SupplierGlobalId { get; set; } public DateTimeOffset PurchaseDate { get; set; } public string? Reference { get; set; } public string? Notes { get; set; } public long TotalCents { get; set; } public string Status { get; set; } = "Confirmed"; public DateTimeOffset CreatedAt { get; set; } public List<PurchaseLine> Lines { get; } = []; }
public sealed class PurchaseLine { public long Id { get; set; } public Guid GlobalId { get; set; } public long PurchaseId { get; set; } public Guid ProductGlobalId { get; set; } public int Quantity { get; set; } public long UnitCostCents { get; set; } public long SubtotalCents { get; set; } public InventoryLot? Lot { get; set; } }
public sealed class InventoryLot { public long Id { get; set; } public Guid GlobalId { get; set; } public long BusinessId { get; set; } public long BranchId { get; set; } public Guid ProductGlobalId { get; set; } public Guid? PurchaseLineGlobalId { get; set; } public DateTimeOffset EntryDate { get; set; } public int InitialQuantity { get; set; } public int AvailableQuantity { get; set; } public long UnitCostCents { get; set; } public bool Active { get; set; } = true; public DateTimeOffset CreatedAt { get; set; } }
public sealed class InventoryMovement { public long Id { get; set; } public Guid GlobalId { get; set; } public long BusinessId { get; set; } public long BranchId { get; set; } public Guid ProductGlobalId { get; set; } public DateTimeOffset MovementDate { get; set; } public string Type { get; set; } = ""; public int QuantityDelta { get; set; } public int PreviousStock { get; set; } public int NewStock { get; set; } public Guid ReferenceGlobalId { get; set; } public long UserId { get; set; } public long DeviceId { get; set; } public string? Notes { get; set; } }
public sealed class Sale { public long Id { get; set; } public Guid GlobalId { get; set; } public Guid IdempotencyKey { get; set; } public long BusinessId { get; set; } public long BranchId { get; set; } public long DeviceId { get; set; } public long UserId { get; set; } public string Folio { get; set; } = ""; public DateTimeOffset SaleDateTime { get; set; } public long SubtotalCents { get; set; } public long DiscountCents { get; set; } public long TotalCents { get; set; } public long FifoCostCents { get; set; } public long GrossProfitCents { get; set; } public string PaymentMethod { get; set; } = "Cash"; public long? ReceivedCents { get; set; } public long ChangeCents { get; set; } public string Status { get; set; } = "Confirmed"; public DateTimeOffset CreatedAt { get; set; } public DateTimeOffset? CancelledAt { get; set; } public string? CancellationReason { get; set; } public long? CancelledByUserId { get; set; } public List<SaleLine> Lines { get; } = []; }
public sealed class SaleLine { public long Id { get; set; } public Guid GlobalId { get; set; } public long SaleId { get; set; } public Guid ProductGlobalId { get; set; } public int Quantity { get; set; } public long UnitPriceCents { get; set; } public long TotalCents { get; set; } public long FifoCostCents { get; set; } public List<SaleLotAllocation> Lots { get; } = []; }
public sealed class SaleLotAllocation { public long Id { get; set; } public Guid GlobalId { get; set; } public long SaleLineId { get; set; } public Guid InventoryLotGlobalId { get; set; } public int Quantity { get; set; } public long UnitCostCents { get; set; } public long TotalCostCents { get; set; } }
public sealed class CashSession { public long Id { get; set; } public Guid GlobalId { get; set; } public long BusinessId { get; set; } public long BranchId { get; set; } public long DeviceId { get; set; } public long UserId { get; set; } public DateTimeOffset OpenedAt { get; set; } public long OpeningBalanceCents { get; set; } public string Status { get; set; } = "Open"; public DateTimeOffset? ClosedAt { get; set; } public long? CountedCashCents { get; set; } public long? ExpectedCashCents { get; set; } public long? DifferenceCents { get; set; } public DateTimeOffset UpdatedAt { get; set; } }
public sealed class Expense { public long Id { get; set; } public Guid GlobalId { get; set; } public long BusinessId { get; set; } public long BranchId { get; set; } public long DeviceId { get; set; } public long UserId { get; set; } public DateTimeOffset ExpenseDate { get; set; } public string Concept { get; set; } = ""; public string? Category { get; set; } public long AmountCents { get; set; } public string PaymentMethod { get; set; } = "Cash"; public string? Notes { get; set; } public DateTimeOffset CreatedAt { get; set; } }
public sealed class InboundOperation { public long Id { get; set; } public long BusinessId { get; set; } public Guid OperationGlobalId { get; set; } public string EntityType { get; set; } = ""; public Guid EntityGlobalId { get; set; } public string Operation { get; set; } = ""; public int PayloadVersion { get; set; } public string PayloadJson { get; set; } = "{}"; public DateTimeOffset ReceivedAt { get; set; } }
public sealed class SyncChange { public long Id { get; set; } public long BusinessId { get; set; } public string EntityType { get; set; } = ""; public Guid EntityGlobalId { get; set; } public string Operation { get; set; } = ""; public long Version { get; set; } public string PayloadJson { get; set; } = "{}"; public DateTimeOffset CreatedAt { get; set; } }
public sealed class RefreshToken { public long Id { get; set; } public long BusinessId { get; set; } public long UserId { get; set; } public long DeviceId { get; set; } public string TokenHash { get; set; } = ""; public DateTimeOffset CreatedAt { get; set; } public DateTimeOffset ExpiresAt { get; set; } public DateTimeOffset? RevokedAt { get; set; } }
public sealed class DeviceEnrollmentToken { public long Id { get; set; } public Guid GlobalId { get; set; } = Guid.NewGuid(); public string TokenHash { get; set; } = ""; public long BusinessId { get; set; } public long BranchId { get; set; } public long CreatedByUserId { get; set; } public DateTimeOffset CreatedAt { get; set; } public DateTimeOffset ExpiresAt { get; set; } public DateTimeOffset? UsedAt { get; set; } public long? DeviceId { get; set; } public DateTimeOffset? RevokedAt { get; set; } }
