import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:pos_app/core/app_services.dart';
import 'package:pos_app/features/first_run/data/enrollment_repository.dart';
import 'package:pos_app/features/first_run/data/first_run_service.dart';

class FirstRunScreen extends StatefulWidget {const FirstRunScreen({super.key});@override State<FirstRunScreen> createState()=>_FirstRunScreenState();}
class _FirstRunScreenState extends State<FirstRunScreen>{bool _busy=false;@override void initState(){super.initState();_redirect();}Future<void> _redirect() async {if(await FirstRunService(appDatabase).configured()&&mounted)context.go('/login');}
 @override Widget build(BuildContext context)=>Scaffold(body:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:560),child:Card(child:Padding(padding:const EdgeInsets.all(32),child:Column(mainAxisSize:MainAxisSize.min,children:[Text('BIENVENIDO',style:Theme.of(context).textTheme.headlineMedium),const SizedBox(height:28),FilledButton.icon(onPressed:_busy?null:()=>_newBusiness(context),icon:const Icon(Icons.store),label:const Text('CONFIGURAR NUEVO NEGOCIO')),const SizedBox(height:16),OutlinedButton.icon(onPressed:_busy?null:()=>_enroll(context),icon:const Icon(Icons.cloud_download),label:const Text('CONECTAR A NEGOCIO EXISTENTE'))]))))));
 Future<void> _newBusiness(BuildContext context) async {final values=await _form(context,['Nombre del negocio','Nombre administrador','Usuario','Contraseña','Nombre dispositivo'],secretIndex:3);if(values==null)return;setState(()=>_busy=true);try{await FirstRunService(appDatabase).createBusiness(businessName:values[0],adminName:values[1],username:values[2],password:values[3],deviceName:values[4]);if(mounted)context.go('/login');}finally{if(mounted)setState(()=>_busy=false);}}
 Future<void> _enroll(BuildContext context) async {final values=await _form(context,['Código de invitación','Usuario administrador','Contraseña','Nombre dispositivo'],secretIndex:2);if(values==null)return;setState(()=>_busy=true);try{await EnrollmentRepository(appDatabase,cloudApiClient).redeem(code:values[0],username:values[1],password:values[2],deviceName:values[3]);if(mounted)context.go('/cloud-admin');}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('No fue posible conectar el dispositivo. Verifica invitación y credenciales.')));}finally{if(mounted)setState(()=>_busy=false);}}
 Future<List<String>?> _form(BuildContext context,List<String> labels,{required int secretIndex}) async {final c=List.generate(labels.length,(_)=>TextEditingController());final result=await showDialog<List<String>>(context:context,builder:(d)=>AlertDialog(title:Text(labels.length==5?'Nuevo negocio':'Conectar dispositivo'),content:SizedBox(width:440,child:Column(mainAxisSize:MainAxisSize.min,children:[for(var i=0;i<labels.length;i++)Padding(padding:const EdgeInsets.only(bottom:10),child:TextField(controller:c[i],obscureText:i==secretIndex,decoration:InputDecoration(labelText:labels[i],border:const OutlineInputBorder())))])),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(d,c.map((e)=>e.text).toList()),child:const Text('Continuar'))]));for(final x in c)x.dispose();return result;}
}
